app: main.o BitwiseFunction.o ChoseMove.o Constants.o coutBoard.o Eval.o Game.o Global.o initBoard.o LegalMoves.o MakeMove.o MouseControl.o SqNameToNb.o  	
	g++ main.o BitwiseFunction.o ChoseMove.o Constants.o coutBoard.o Eval.o Game.o Global.o initBoard.o LegalMoves.o MakeMove.o MouseControl.o SqNameToNb.o -o app

main.o : main.cpp
	g++ -c -Iinclude main.cpp

BitwiseFunction.o : src/BitwiseFunction.cpp
	g++ -c -Iinclude src/BitwiseFunction.cpp

ChoseMove.o : src/ChoseMove.cpp
	g++ -c -Iinclude src/ChoseMove.cpp

Constants.o : src/Constants.cpp
	g++ -c -Iinclude src/Constants.cpp

coutBoard.o : src/coutBoard.cpp
	g++ -c -Iinclude src/coutBoard.cpp

Eval.o : src/Eval.cpp
	g++ -c -Iinclude src/Eval.cpp

Game.o : src/Game.cpp
	g++ -c -Iinclude src/Game.cpp

Global.o : src/Global.cpp
	g++ -c -Iinclude src/Global.cpp

initBoard.o : src/initBoard.cpp
	g++ -c -Iinclude src/initBoard.cpp

LegalMoves.o : src/LegalMoves.cpp
	g++ -c -Iinclude src/LegalMoves.cpp

MakeMove.o : src/MakeMove.cpp
	g++ -c -Iinclude src/MakeMove.cpp

MouseControl.o : src/MouseControl.cpp
	g++ -c -Iinclude src/MouseControl.cpp

SqNameToNb.o : src/SqNameToNb.cpp
	g++ -c -Iinclude src/SqNameToNb.cpp